package InterfacesFolder;

import LogicFolder.BookModifier;
import java.util.HashMap;
import javax.swing.DefaultListModel;

public class AdministratorDialog extends javax.swing.JDialog {

    
    private BookModifier bookModif = new BookModifier();
    
    private int selection = -1;
    private DefaultListModel model = new DefaultListModel();

    private String defaultinputBooknameText = "Indique el nombre del libro";
    private String selectedBook;
    
    /**
     * Creates new form AdministratorDialog
     */
    public AdministratorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        hideErrorlbl();
        listBooks.setModel(model);
        
        fillInitialList();
        
    }

    
    public void hideErrorlbl() {
        lblErrorNoName.setVisible(false);
        lblErrorNoSelection.setVisible(false);
    }
    
    public void fillInitialList() {
        HashMap<String, HashMap> bookHashMap = bookModif.getBookList();
        for (String key : bookHashMap.keySet() ) {
            model.addElement(key);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        textTitle = new javax.swing.JLabel();
        txtSubtitle = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        txtBookList = new javax.swing.JLabel();
        btnDeleteBook = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();
        lblBookCounter = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBooks = new javax.swing.JList<>();
        lblErrorNoSelection = new javax.swing.JLabel();
        lblErrorNoName = new javax.swing.JLabel();
        inputBookname = new javax.swing.JTextField();
        pnlFooter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(14, 78, 84));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textTitle.setFont(new java.awt.Font("Grantha Sangam MN", 1, 55)); // NOI18N
        textTitle.setForeground(new java.awt.Color(255, 255, 255));
        textTitle.setText("BookLife");
        pnlHeader.add(textTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 260, -1));

        txtSubtitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 2, 24)); // NOI18N
        txtSubtitle.setForeground(new java.awt.Color(232, 250, 242));
        txtSubtitle.setText("Venta y Alquiler de Libros");
        pnlHeader.add(txtSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBookList.setFont(new java.awt.Font("Kohinoor Devanagari", 0, 24)); // NOI18N
        txtBookList.setForeground(new java.awt.Color(0, 0, 0));
        txtBookList.setText("Lista de libros disponibles");
        pnlBackground.add(txtBookList, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        btnDeleteBook.setBackground(new java.awt.Color(124, 204, 182));
        btnDeleteBook.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 17)); // NOI18N
        btnDeleteBook.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteBook.setText("Eliminar libro");
        btnDeleteBook.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 153, 102))); // NOI18N
        btnDeleteBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });
        pnlBackground.add(btnDeleteBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 180, 50));

        btnAddBook.setBackground(new java.awt.Color(124, 204, 182));
        btnAddBook.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 17)); // NOI18N
        btnAddBook.setForeground(new java.awt.Color(0, 0, 0));
        btnAddBook.setText("Agregar libro");
        btnAddBook.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 153, 102))); // NOI18N
        btnAddBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        pnlBackground.add(btnAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 180, 50));

        txtWelcome.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(0, 0, 0));
        txtWelcome.setText("Bienvenido Administrador");
        pnlBackground.add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblBookCounter.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblBookCounter.setForeground(new java.awt.Color(0, 0, 0));
        lblBookCounter.setText("Cantidad de libros:");
        pnlBackground.add(lblBookCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        listBooks.setBackground(new java.awt.Color(245, 245, 245));
        listBooks.setForeground(new java.awt.Color(0, 43, 51));
        listBooks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listBooks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listBooksValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listBooks);

        pnlBackground.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 290, 320));

        lblErrorNoSelection.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorNoSelection.setText("Seleccione solamente un libro");
        pnlBackground.add(lblErrorNoSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, -1, -1));

        lblErrorNoName.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorNoName.setText("No se ha escrito el nombre de ningún libro");
        pnlBackground.add(lblErrorNoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        inputBookname.setBackground(new java.awt.Color(245, 245, 245));
        inputBookname.setFont(new java.awt.Font("Kohinoor Bangla", 0, 18)); // NOI18N
        inputBookname.setForeground(new java.awt.Color(0, 0, 0));
        inputBookname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputBookname.setText("Indique el nombre del libro");
        inputBookname.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        inputBookname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputBookname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputBooknameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputBooknameMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputBooknameMouseEntered(evt);
            }
        });
        inputBookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBooknameActionPerformed(evt);
            }
        });
        pnlBackground.add(inputBookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 350, 40));

        pnlFooter.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Murillo Anchia Pamela");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                        .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        hideErrorlbl();
        
        if (selection >= 0) {
            bookModif.deleteBook( selectedBook );
            model.removeElementAt( selection );
            
        } else {
            lblErrorNoSelection.setVisible(true);
        } 
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        hideErrorlbl();
        
        if (inputBookname.getText() != defaultinputBooknameText) {
            
            String[] bookData = new String[3];

            bookData[0] = inputBookname.getText();
            bookData[1] = 0 + "";
            bookData[2] = 0 + "";

            bookModif.addBook(bookData);
            
            model.addElement(bookData[0]);
            
        } else {
            lblErrorNoName.setVisible(true);
        }
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void listBooksValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listBooksValueChanged
        selection = listBooks.getSelectedIndex();
        selectedBook = model.getElementAt(selection).toString();
    }//GEN-LAST:event_listBooksValueChanged

    private void inputBooknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputBooknameMouseClicked
        hideErrorlbl();

    }//GEN-LAST:event_inputBooknameMouseClicked

    private void inputBooknameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputBooknameMouseExited
        if ( inputBookname.getText().equals("") ) {
            inputBookname.setText(defaultinputBooknameText);
        }
    }//GEN-LAST:event_inputBooknameMouseExited

    private void inputBooknameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputBooknameMouseEntered
        if ( inputBookname.getText().equals(defaultinputBooknameText) ) {
            inputBookname.setText("");
        }
    }//GEN-LAST:event_inputBooknameMouseEntered

    private void inputBooknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBooknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBooknameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdministratorDialog dialog = new AdministratorDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JTextField inputBookname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBookCounter;
    private javax.swing.JLabel lblErrorNoName;
    private javax.swing.JLabel lblErrorNoSelection;
    private javax.swing.JList<String> listBooks;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JLabel textTitle;
    private javax.swing.JLabel txtBookList;
    private javax.swing.JLabel txtSubtitle;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
