package InterfacesFolder;

import LogicFolder.ArchiveManager;
import java.util.ArrayList;
import java.util.HashMap;


public class LoginFrame extends javax.swing.JFrame {

    
    private HashMap<String, HashMap> mainHashMap = new HashMap<String, HashMap>();
    private ArchiveManager archiveManager = new ArchiveManager();
    
    private String defaultUsernameText = "Indique aquí su nombre";
    private String defaultPasswordText = "*********";
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        resetLabels();
        getUserFile();
        
        btnLogin.setOpaque(true);
        btnRegister.setOpaque(true);
    }

    public void resetLabels() {
        lblErrorUser.setVisible(false);
        lblErrorPassword.setVisible(false);
    }
    
    public void getUserFile() {
        archiveManager.createFileUsers();
        ArrayList userList = archiveManager.readInFile("users");
        
        for (int line = 0; userList.size() > line; line++) {
            String newLine = userList.get(line).toString();
            String[] newLineArray = newLine.split(", ");
            
            HashMap<String, String> subHashMap = new HashMap<String, String>();
            subHashMap.put("type", newLineArray[1]);
            subHashMap.put("password", newLineArray[2]);
            
            mainHashMap.put(newLineArray[0], subHashMap);
        }
    }
    
    
    public boolean confirmIfUserExist(String userName) {
        boolean doesItExist = mainHashMap.containsKey(userName) && userName != defaultUsernameText;
        return doesItExist;
    }
    
    public boolean isThePasswordValid(String userName, String password) {
        boolean isValid = false;
        HashMap<String, String> userInfo = mainHashMap.get(userName);
        String filePassword = userInfo.get("password");
        
        if (filePassword.equals(password)) {
            isValid = true;
        }
        
        return isValid;
    }

    
    public void addUser(String userName, String password) {
        archiveManager.createFileUsers();
        archiveManager.writeInFile("users", userName + ", user, " + password);
        getUserFile();
    }
    
    
    public void openNewWindow(String userName) {
        HashMap<String, String> userInfo = mainHashMap.get(userName);
        String userType = userInfo.get("type"); //This will get either "administrator" or "user"
        
        if (userType.equals("administrator")) {
            AdministratorDialog newWindow = new AdministratorDialog(this, true);
            newWindow.setVisible(true);
        } else {
            UserDialog newWindow = new UserDialog(this, true);
            newWindow.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblError1 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        txtSubtitle = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        textTitle = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        inputUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegister = new javax.swing.JButton();
        lblErrorUser = new javax.swing.JLabel();
        BookIcon = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtSubtitle1 = new javax.swing.JLabel();

        lblError1.setBackground(new java.awt.Color(255, 255, 255));
        lblError1.setForeground(new java.awt.Color(204, 0, 0));
        lblError1.setText("La contraseña no es válida para este nombre de usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1100, 750));
        setMinimumSize(new java.awt.Dimension(1100, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(14, 78, 84));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSubtitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 36)); // NOI18N
        txtSubtitle.setForeground(new java.awt.Color(234, 248, 234));
        txtSubtitle.setText("Porque los libros son parte de vivir");
        pnlHeader.add(txtSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 600, 60));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 130));

        pnlFooter.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Murillo Anchia Pamela");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(952, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(pnlFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, -1, 40));

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textTitle.setFont(new java.awt.Font("Grantha Sangam MN", 1, 55)); // NOI18N
        textTitle.setForeground(new java.awt.Color(0, 0, 0));
        textTitle.setText("BookLife");
        pnlBackground.add(textTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, -1));

        lblPassword.setFont(new java.awt.Font("Kohinoor Bangla", 0, 17)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblPassword.setText("Contraseña");
        pnlBackground.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        lblUsername.setFont(new java.awt.Font("Kohinoor Bangla", 0, 17)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setText("Nombre de Usuario");
        pnlBackground.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        inputPassword.setBackground(new java.awt.Color(245, 245, 245));
        inputPassword.setFont(new java.awt.Font("Kohinoor Bangla", 1, 15)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(102, 102, 102));
        inputPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputPassword.setText("***");
        inputPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        inputPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputPasswordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputPasswordMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputPasswordMouseEntered(evt);
            }
        });
        pnlBackground.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 250, 40));

        inputUsername.setBackground(new java.awt.Color(245, 245, 245));
        inputUsername.setFont(new java.awt.Font("Kohinoor Bangla", 2, 15)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(102, 102, 102));
        inputUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputUsername.setText("Indique aquí su nombre");
        inputUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        inputUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputUsernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputUsernameMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputUsernameMouseEntered(evt);
            }
        });
        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });
        pnlBackground.add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 40));
        pnlBackground.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 250, 10));
        pnlBackground.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 250, 10));

        btnRegister.setBackground(new java.awt.Color(124, 204, 182));
        btnRegister.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 17)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(0, 0, 0));
        btnRegister.setText("Registrarse");
        btnRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 204, 153))); // NOI18N
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        pnlBackground.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 140, 50));

        lblErrorUser.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorUser.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorUser.setText("Nombre de usuario no válido");
        pnlBackground.add(lblErrorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        BookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogicFolder/BookIcon.png"))); // NOI18N
        BookIcon.setText("jLabel4");
        pnlBackground.add(BookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 860, 420));

        lblErrorPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorPassword.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPassword.setText("La contraseña no es válida para este nombre de usuario");
        pnlBackground.add(lblErrorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        btnLogin.setBackground(new java.awt.Color(124, 204, 182));
        btnLogin.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 17)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 153, 102))); // NOI18N
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlBackground.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 140, 50));

        txtSubtitle1.setFont(new java.awt.Font("Hiragino Mincho ProN", 2, 24)); // NOI18N
        txtSubtitle1.setForeground(new java.awt.Color(0, 51, 51));
        txtSubtitle1.setText("Venta y Alquiler de Libros");
        pnlBackground.add(txtSubtitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1100, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        resetLabels();
        
        boolean doesItExist = confirmIfUserExist( inputUsername.getText() ); //If the user exists
        if (doesItExist == false){
            addUser(inputUsername.getText(), String.valueOf(inputPassword.getPassword()) );
            openNewWindow("Normal");
        } else {
            lblErrorUser.setVisible(true);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        resetLabels();
        
        boolean doesItExist = confirmIfUserExist( inputUsername.getText() );
        
        if (doesItExist == true) {
            boolean validPassword = isThePasswordValid( inputUsername.getText(), String.valueOf(inputPassword.getPassword()) );
            if (validPassword == true){
                openNewWindow( inputUsername.getText() );
                
            } else { lblErrorPassword.setVisible(true); }
            
        } else { lblErrorUser.setVisible(true); }
    }//GEN-LAST:event_btnLoginActionPerformed

    
    private void inputUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsernameMouseClicked
        resetLabels();
        
    }//GEN-LAST:event_inputUsernameMouseClicked

    
    private void inputPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordMouseClicked
        resetLabels();
        
    }//GEN-LAST:event_inputPasswordMouseClicked

    private void inputUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsernameMouseEntered
        if ( inputUsername.getText().equals(defaultUsernameText) ) {
            inputUsername.setText("");
        }
    }//GEN-LAST:event_inputUsernameMouseEntered

    private void inputUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsernameMouseExited
        if ( inputUsername.getText().equals("") ) {
            inputUsername.setText(defaultUsernameText);
        } 
    }//GEN-LAST:event_inputUsernameMouseExited

    private void inputPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordMouseEntered
        if ( String.valueOf(inputPassword.getPassword()).equals(defaultPasswordText) ) {
            inputPassword.setText("");
        }
    }//GEN-LAST:event_inputPasswordMouseEntered

    private void inputPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordMouseExited
        if ( String.valueOf(inputPassword.getPassword()).equals("") ) {
            inputPassword.setText(defaultPasswordText);
        } 
    }//GEN-LAST:event_inputPasswordMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookIcon;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JLabel textTitle;
    private javax.swing.JLabel txtSubtitle;
    private javax.swing.JLabel txtSubtitle1;
    // End of variables declaration//GEN-END:variables
}
